### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by CarelessChaser** [kaitai-io/kaitai_struct_cpp_stl_runtime#2]
For proper packaging you should make release.

**Comment by GreyCat** [comment]
You mean, setting the version tag for it to appear in GitHub "releases" tab?

**Comment by CarelessChaser** [comment]
Yes.

**Comment by GreyCat** [comment]
Here we go: https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/releases/tag/0.4
How do you intend to package it?

**Comment by CarelessChaser** [comment]
I will make ebuilds for Gentoo. Also, now anyone can prepare packages for his distribution. So, sometimes you should make releases for every project to help other enthusiasts help you.

**Comment by GreyCat** [comment]
There are several thoughts on packaging and release process:

* C++ support and C++ runtime is in relatively early stage of development and probably it's kind of premature to offer it to distributions.
* Probably packaging a compiler itself would be much more useful for distribution end-users. Of course, it is possible to use runtimes without it, but it's not really much of a value — there's just a dozen of very simple functions.
* Compiling it as a dynamic library is, of course, technically possible, but probably won't be very popular. Static link would enable extra optimization options, such as inlining stuff like  `kaitai::kstream::read_s4be()` — which is probably a good thing since these can be called very often when parsing a large structure.
* We do releases (i.e. a proper release event, with release notes, announcing on our site, Twitter account and posting announces to various sites), but that's for [the project as a whole](https://github.com/kaitai-io/kaitai_struct/releases) (plus [a compiler](https://github.com/kaitai-io/kaitai_struct_compiler/releases)), not for individual runtime repositories. Probably it's a good idea to do tagging for all repositories, including tests, runtimes, etc.

**Comment by GreyCat** [comment]
... and last, but not least — thanks for your packaging effort :)
